# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: popcorn 1.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "popcorn"
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Blaine Pace"]
  s.date = "2017-03-18"
  s.description = "Popcorn handles movie library management for you."
  s.email = "blainepace@gmail.com"
  s.executables = ["popcorn"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rvmrc",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/popcorn",
    "lib/popcorn.rb",
    "lib/popcorn/movies.rb",
    "lib/popcorn/settings.rb",
    "popcorn.gemspec",
    "spec/movies_spec.rb",
    "spec/settings_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/sensae/popcorn"
  s.licenses = ["GPL"]
  s.rubygems_version = "2.5.1"
  s.summary = "Popcorn is a movie management program"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>, ["~> 0.19.4"])
      s.add_runtime_dependency(%q<imdb_party>, ["~> 0.8.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.14.6"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.3.3"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<fakefs>, ["~> 0.3.2"])
    else
      s.add_dependency(%q<thor>, ["~> 0.19.4"])
      s.add_dependency(%q<imdb_party>, ["~> 0.8.0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.14.6"])
      s.add_dependency(%q<jeweler>, ["~> 2.3.3"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<fakefs>, ["~> 0.3.2"])
    end
  else
    s.add_dependency(%q<thor>, ["~> 0.19.4"])
    s.add_dependency(%q<imdb_party>, ["~> 0.8.0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.14.6"])
    s.add_dependency(%q<jeweler>, ["~> 2.3.3"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<fakefs>, ["~> 0.3.2"])
  end
end

